services:
  sshwifty:
    image: ghcr.io/snuffy2/sshwifty:latest
    container_name: sshwifty
    restart: unless-stopped
    ports:
      - "8182:8182"
    volumes:
      - ./sshwifty.conf.json:/etc/sshwifty/sshwifty.conf.json:ro
    environment:
      SSHWIFTY_CONFIG: /etc/sshwifty/sshwifty.conf.json
