// Copyright (C) 2019-2026 Ni Rui <ranqus@gmail.com>
// Copyright (C) 2026 Snuffy2
// SPDX-License-Identifier: AGPL-3.0-only

import assert from "assert";
import * as reader from "../stream/reader.js";
import * as strings from "./string.js";

describe("String", () => {
  it("String 1", async () => {
    let s = new strings.String(new Uint8Array(["H", "E", "L", "L", "O"])),
      sBuf = s.buffer();

    let r = new reader.Reader(new reader.Multiple(() => {}), (data) => {
      return data;
    });

    r.feed(sBuf);

    let s2 = await strings.String.read(r);

    assert.deepStrictEqual(s2.data(), s.data());
  });

  it("String 2", async () => {
    let s = new strings.String(
        new Uint8Array([
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
          "H",
          "E",
          "L",
          "L",
          "O",
          "W",
          "O",
          "R",
          "L",
          "D",
        ]),
      ),
      sBuf = s.buffer();

    let r = new reader.Reader(new reader.Multiple(() => {}), (data) => {
      return data;
    });

    r.feed(sBuf);

    let s2 = await strings.String.read(r);

    assert.deepStrictEqual(s2.data(), s.data());
  });
});
