# Copyright (C) 2019-2026 Ni Rui <ranqus@gmail.com>
# Copyright (C) 2026 Snuffy2
# SPDX-License-Identifier: AGPL-3.0-only

name: 'Pull Request Labeler'
on:
  pull_request_target:

jobs:
  labeler:
    name: Pull Request Labeler
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Pull Request Labeler
        uses: srvaroa/labeler@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
